"""tirando campo text

Revision ID: 00bb17df240c
Revises: 2b41ac5bd7b7
Create Date: 2025-03-06 22:11:17.671575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00bb17df240c'
down_revision = '2b41ac5bd7b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.drop_column('text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
