"""Remove column text

Revision ID: 6b14d01a8f61
Revises: 85ade5056e80
Create Date: 2025-03-07 16:38:31.750823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b14d01a8f61'
down_revision = '85ade5056e80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.drop_column('text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.TEXT(), server_default=sa.text("'a'::text"), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
