"""Remove unique constraint from nome

Revision ID: 6cfdfdcfaf8c
Revises: 36dec72f6cf2
Create Date: 2025-03-05 11:44:16.635234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cfdfdcfaf8c'
down_revision = '36dec72f6cf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint('usuario_nome_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_unique_constraint('usuario_nome_key', ['nome'])

    # ### end Alembic commands ###
