"""removendo coluna text de novo

Revision ID: 85ade5056e80
Revises: c3ec3a9b8bb8
Create Date: 2025-03-06 22:35:52.782186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85ade5056e80'
down_revision = 'c3ec3a9b8bb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.drop_column('text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
