"""Atualizando tabela de links

Revision ID: 94285c536840
Revises: f652bff32d87
Create Date: 2025-03-05 13:12:31.860942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94285c536840'
down_revision = 'f652bff32d87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
