"""adicionando coluna text

Revision ID: c3ec3a9b8bb8
Revises: 00bb17df240c
Create Date: 2025-03-06 22:29:12.378567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3ec3a9b8bb8'
down_revision = '00bb17df240c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.drop_column('text')

    # ### end Alembic commands ###
